default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: recipebox_development

test:
  <<: *default
  database: recipebox_test

production:
  <<: *default
  database: recipebox_production
